FROM rust:latest

RUN rustup target add x86_64-unknown-linux-musl \
 && apt-get update \
 && apt-get install -y --no-install-recommends musl-tools \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY src/ src/
COPY Cargo.toml .

RUN cargo build --release --target x86_64-unknown-linux-musl
RUN find

# Binaries land in target/x86_64-unknown-linux-musl/release/
